### PR TITLE
Fix CIs

### PR DESCRIPTION
**Pull request by SConaway**

### CODE REVIEW

**Comment by somebody1234** [comment]
Oh pls add `sudo -H pip3 install brotli` too

**Comment by SConaway** [comment]
Will Do :-)

**Comment by somebody1234** [comment]
@SConaway :/ it's not working

**Comment by somebody1234** [comment]
I don't think `"%PYTHON%\\python.exe -m 'pip3 install regex brotli'"` is how you install it lol

**Comment by SConaway** [comment]
Is there any reason Travis CI forces `dist: precise`?

**Comment by somebody1234** [comment]
It's in the config apparently

**Comment by somebody1234** [comment]
So just add `"dist": "trusty"` to the config, unless `"dist": "precise"` is there in which case just remove that

**Comment by somebody1234** [comment]
Also AppVeyor is still broken :/

**Comment by SConaway** [comment]
I Know working on one at a time then will squash.

**Comment by SConaway** [comment]
Mac CI is hanging. Again

**Comment by somebody1234** [comment]
Mac CI looks fine to me

**Comment by SConaway** [comment]
Yes it does. I'm going to close this and create another pr for adding a `requirements.txt` which should help fix this.

**Pull request closed without merging**
